# Generated by Django 2.0.5 on 2018-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_rulebook_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulebook',
            old_name='recomended_age_max',
            new_name='recommended_age_max',
        ),
        migrations.RenameField(
            model_name='rulebook',
            old_name='recomended_age_min',
            new_name='recommended_age_min',
        ),
    ]
